feat: Prettier
OurUncomplicatedTemplates/fastify-prisma-redis-swagger-jwt-template pull request #20
Opened 2023-09-17 17:13 UTC by kristianbinau

## Description
Installed Prettier and ran it : )

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [x] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-09-17 19:06 UTC, frederikpyt requested changes
Have you looked at https://mskelton.medium.com/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df

He seems to have gotten it working

2023-09-17 19:06 UTC, frederikpyt commented on .prettierignore
> +prisma
```suggestion
prisma
build
```

2023-09-18 18:44 UTC, kristianbinau commented
> Have you looked at https://mskelton.medium.com/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df
> 
> He seems to have gotten it working

Okay that's good, you decide if commit message is good haha

2023-09-19 04:36 UTC, frederikpyt approved these changes
Pretty 🥰

2023-09-19 05:38 UTC, merged